'version': '3'

services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=omnistack_saas
    ports:
      - 3306:3306
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - '6379:6379'
networks:
  app-network:
    external: true
